### ISSUE TITLE
Nothing...

### ISSUE THREAD

**Issue by PersonForever** [burmaraider/DAT-Reader#4]

**Comment by ManevogerKrCode** [comment]
or this https://github.com/AkvenJan/LithTech-DAT-UV-Vectors-Upscaler

**Comment by burmaraider** [comment]
It's in the works, not implemented yet. Those are for the wrong version. NOLF2 uses a different format. I have it mapped, but not implemented yet.

**Comment by ManevogerKrCode** [comment]
> It's in the works, not implemented yet. Those are for the wrong version. NOLF2 uses a different format. I have it mapped, but not implemented yet.

Well, I wish you good luck. I just tested it. The dat of nolf2 is indeed a little different, but I tried to use nolf2 to run datv85 in other games and it worked.

**Comment by ManevogerKrCode** [comment]
very strange

**Comment by burmaraider** [comment]
> very strange

I wouldn't say strange. A v85 is a v85 and the Jupiter engine will load these without issue. Expected behaviour more like it. V85 will be supported one day, just not right now. Lots more bugs to get out before we get there. But the v85 format is well known and we don't have to guess on anything.
